version: "3.5"

services:
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:${CARDANO_NODE_OGMIOS_VERSION:-v5.1.0}-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    restart: on-failure
    volumes:
      - node-db:/db

  dgraph:
    image: dgraph/standalone:v21.03.0
    ports:
      - 5080:5080
      - 6080:6080
      - 8080:8080
      - 9080:9080
    volumes:
      - dgraph:/dgraph

  ratel:
    image: dgraph/ratel:v21.03.0
    ports:
      - 8000:8000

volumes:
  dgraph:
  node-db: