apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"RedirectConfig":{"Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_301"},"Type":"redirect"}'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/aws-region: eu-central-1
    external-dns.alpha.kubernetes.io/set-identifier: eu-central-1-dev-preview-proxy
  labels:
    app: coingecko-proxy

  name: cardanojs-coingecko-proxy
spec:
  ingressClassName: alb
  rules:
    - host: coingecko.dev-preview.eks.lw.iog.io
      http:
        paths:
          - backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
            path: /
            pathType: Prefix
          - backend:
              service:
                name: cardanojs-coingecko-proxy
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - coingecko.dev-preview.eks.lw.iog.io
