apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cardanojs-sdk
  annotations:
    config.kubernetes.io/local-config: 'true'
namespace: dev-preview
namePrefix: dev-preview-
commonLabels:
  network: preview
