apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stake-pool-projector
    network: preview
    release: dev-preview-cardanojs
  name: dev-preview-cardanojs-stake-pool-projector
spec:
  selector:
    matchLabels:
      app: stake-pool-projector
      network: preview
      release: dev-preview-cardanojs
  template:
    metadata:
      labels:
        app: stake-pool-projector
        network: preview
        release: dev-preview-cardanojs
    spec:
      containers:
        - args:
            - start-projector
          env:
            - name: LOGGER_MIN_SEVERITY
              value: debug
            - name: NETWORK
              value: preview
            - name: NETWORK_INFO_PROVIDER_URL
              value: http://dev-preview-cardanojs-backend.dev-preview.svc.cluster.local
            - name: OGMIOS_SRV_SERVICE_NAME
              value: dev-preview-cardano-stack.dev-preview.svc.cluster.local
            - name: POSTGRES_DB
              value: stakepool
            - name: POSTGRES_HOST
              value: dev-preview-dbsync-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: stakepool-owner-user.dev-preview-dbsync-db.credentials.postgresql.acid.zalan.do
            - name: POSTGRES_POOL_MAX
              value: "2"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_SSL
              value: "true"
            - name: POSTGRES_SSL_CA_FILE
              value: /tls/ca.crt
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: stakepool-owner-user.dev-preview-dbsync-db.credentials.postgresql.acid.zalan.do
            - name: PROJECTION_NAMES
              value: stake-pool,stake-pool-metadata-job,stake-pool-metrics-job,stake-pool-rewards-job
          image: FIXME-ADD-LATEST-IMAGE-REFERENCE
          livenessProbe:
            httpGet:
              path: /v1.0.0/live
              port: 3000
            timeoutSeconds: 5
          name: stake-pool-projector
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              cpu: 700m
              memory: 300Mi
            requests:
              cpu: 700m
              memory: 150Mi
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
            - mountPath: /tls
              name: tls
      imagePullSecrets:
        - name: dockerconfigjson
      volumes:
        - name: tls
          secret:
            secretName: postgresql-server-cert
