name: nightly

on:
  workflow_dispatch:
  schedule:
    # Every day 00:00 UTC
    - cron:  '0 0 * * *'

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: ðŸ“¥ Checkout repository
      uses: actions/checkout@v2.3.3
      with:
        # Fetch all history for all tags and branches
        fetch-depth: 0
        ref: nightly
        submodules: true

    - name: â¬ Merge in master
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge origin/master
        git push --force

    - name: ðŸ§° Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.17
        registry-url: 'https://registry.npmjs.org'

    - name: ðŸ’½ Install dependencies
      run: |
        yarn install --immutable --inline-builds --mode=skip-build
        git checkout yarn-project.nix

    - name: ðŸ“ Count changed packages
      uses: sergeysova/jq-action@v2
      id: changed
      with:
        cmd: yarn run lerna changed --json | jq -ne 'input? // 0 | length'

    - name: ðŸ“¤ Publish
      if: steps.changed.outputs.value > 0
      run: |
        yarn build
        yarn publish:nightly --loglevel silly
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
        NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
