name: nightly-test

on:
  workflow_run:
    workflows: [nightly-merge]
    types:
      - completed

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        nodejs: [ 14, 16, 18.12.0, latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: ğŸ“¥ Checkout repository
      uses: actions/checkout@v3
      with:
        ref: nightly

    - name: ğŸ§° Setup Node.js
      uses: actions/setup-node@v3
      with:
        check-latest: true
        node-version: ${{ matrix.nodejs }}
        registry-url: 'https://registry.npmjs.org'

    - name: ğŸ’½ Install dependencies
      run: |
        yarn install --immutable --inline-builds --mode=skip-build

    - name: ğŸ”¨ Build
      run: |
        yarn build

    - name: ğŸ”¬ Test
      run: |
        yarn lint
        yarn test:build:verify
        yarn test --forceExit    
