name: nightly-publish

on:
  workflow_run:
    workflows: [nightly-test]
    types:
      - completed

jobs:
  cancel-self-run:
    name: "Cancel the self workflow run"
    if: ${{ github.event.workflow_run.conclusion != 'success' }} 
    runs-on: ubuntu-20.04
    steps:
      - name: "Cancel the self workflow run"
        uses: potiuk/cancel-workflow-runs@master
        with:
          cancelMode: self
          token: ${{ secrets.BOT_GH_TOKEN }}
          notifyPRCancel: false
    
  publish:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
    - name: ðŸ“¥ Checkout repository
      uses: actions/checkout@v3
      with:
        # Fetch all history for all tags and branches
        fetch-depth: 0
        ref: nightly

    - name: ðŸ§° Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.0
        registry-url: 'https://registry.npmjs.org'

    - name: ðŸ’½ Install dependencies
      run: |
        yarn install --immutable --inline-builds --mode=skip-build
        git checkout yarn-project.nix

    - name: ðŸ“ Count changed packages
      id: precondition
      run: |
        CHANGED=$(yarn run lerna changed --json | jq -ne 'input? // 0 | length')
        echo "$CHANGED packages changed"
        echo "::set-output name=changed::$(($CHANGED))"

    - name: ðŸ“¤ Publish
      if: steps.precondition.outputs.changed > 0
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        yarn build
        yarn publish:nightly --loglevel silly
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
        NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
